# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React Native CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  # build:
  #   runs-on: macos-latest

  #   strategy:
  #     matrix:
  #       node-version: [17.x]
  #       # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v2

  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: "npm"

  #     - run: npm ci
  #     - run: npm run build --if-present
  #     - run: npm run test

  # test:
  #   needs: build

  #   runs-on: macos-latest

  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v2

  #     # - name: Use Node.js to run test
  #     #   uses: actions/setup-node@v2

  #     - name: Run Test
  #       run: |
  #         npm ci
  #         npm run test

  # e2e_ios:
  #   # needs: build

  #   runs-on: macos-latest

  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v2

  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 16.x
  #         cache: "npm"

  #     - name: Install iOS Plaform dependencies
  #       run: |
  #         brew tap wix/brew
  #         brew install applesimutils

  #     - name: Install project npm dependencies
  #       run: npm ci

  #     - name: Pod install
  #       run: |
  #         cd ./ios
  #         pod install
  #         cd ..
      
  #     - name: Detox build
  #       run: npm run e2e:build ios.sim.debug

  #     - name: Detox test
  #       run: |
  #         npm start &
  #         METRO_BUNDLER_PID=$!
  #         npm run e2e:test ios.sim.debug
  #         DETOX_EXIT_CODE=$?
  #         kill $METRO_BUNDLER_PID
  #         exit $DETOX_EXIT_CODE

  e2e_android:
    # needs: build

    runs-on: macos-latest

    strategy:
      matrix:
        java-version: [8, 17]
        # api-level: [29, 31, 32]
        # target: [default, google_apis]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 16.x
      #     cache: "npm"

      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - run: |
          java -version
          echo $ANDROID_HOME

      - name: Install emulator and create avd
        run: | 
          $ANDROID_HOME/tools/bin/sdkmanager --install emulator
          $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-31;default;x86_64"
          $ANDROID_HOME/tools/bin/sdkmanager --licenses
          $ANDROID_HOME/tools/bin/avdmanager create avd -n Pixel_5_API_31 -d pixel --package "system-images;android-31;default;x86_64"

      # - name: Install project npm dependencies
      #   run: npm ci

      # - name: Detox build
      #   run: npm run e2e:build android.emu.debug

      # - name: Detox test
      #   uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     api-level: 31
      #     target: default
      #     arch: x86_64
      #     profile: pixel
      #     avd-name: Pixel_5_API_31
      # - shell: bash
      #   run: |
      #     npm start &
      #     METRO_BUNDLER_PID=$!
      #     npm run e2e:test android.emu.debug
      #     DETOX_EXIT_CODE=$?
      #     kill $METRO_BUNDLER_PID
      #     exit $DETOX_EXIT_CODE
