# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React Native CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  # build:
  #   runs-on: macos-latest

  #   strategy:
  #     matrix:
  #       node-version: [17.x]
  #       # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v2

  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: "npm"

  #     - run: npm ci
  #     - run: npm run build --if-present
  #     - run: npm run test

  # test:
  #   needs: build

  #   runs-on: macos-latest

  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v2

  #     # - name: Use Node.js to run test
  #     #   uses: actions/setup-node@v2

  #     - name: Run Test
  #       run: |
  #         npm ci
  #         npm run test

  e2e_ios:
    # needs: build

    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
          cache: "npm"

      - name: Install iOS Plaform dependencies
        run: |
          xcode-select --install
          brew tap wix/brew
          brew install applesimutils

      - name: Install project npm dependencies
        run: npm ci

      - name: Pod install
        run: |
          cd ./ios
          pod install
          cd ..
      
      - name: Detox build
        run: npm run e2e:build ios.sim.debug

      - name: Detox test
        run: npm run e2e:test ios.sim.debug
